# -*- coding: utf-8 -*-
"""ML-MINOR-APRIL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MJpao9TL1DwFsQyVl0O3LHpS0Vsu2ITc

#IMPORTING THE CSV FILE
"""

import pandas as pd
df=pd.read_csv("/content/DataCoSupplyChainDataset.csv",encoding='unicode_escape')
df

"""#DATA ANALYSIS"""

df.info()

df.isnull().sum()



df.tail()

df[25000:25100]

df[["Delivery Status","Order City","Order Country"]]

df.loc[24000:25000,"Delivery Status"]

df['Delivery Status'].value_counts()

df['Order Country'].value_counts()

df['Order Country']



"""# PENDING SALES IN INDIA AND CITIES"""

india_count=df[df['Order Country'].str.contains('India')]
india_count

india_count.info()

india_count['Delivery Status'].value_counts()

india_count['Order City'].value_counts()

india_count['Order City'].unique()

india_count['Order Status'].value_counts()

"""india has 537 pending orders"""



"""#SUSPECTED FRAUD """

sus_fraud=df[df['Order Status'].str.contains('SUSPECTED_FRAUD')]
sus_fraud

sus_fraud['Order Country'].value_counts()

"""estados unidos has most suspected fraud with 573"""





"""#PRODUCT WITH LARGEST DISCOUNT"""

discount=df.sort_values(by="Order Item Discount",ascending=False)
discount[["Order Item Discount","Product Name","Product Card Id"]].head(50)

"""SOLE E35 Elliptical	 has biggest discount with 500

`
```

#real > schedule
"""

df[df['Delivery Status'].str.contains('Late delivery')]['Order Status'].value_counts()

"""there are 34199 completed late deleveries....ie shipping real (Real) > Days for shipment (Scheduled)?
 
"""