# -*- coding: utf-8 -*-
"""important codes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UT9evvu7Ls3Z9nNYXtOpfgcetaB5l49B

#pandas
"""



import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Copy of bloodp.csv")
df

df.info()

df.head()

df.tail()

df.sample(frac=0.3)

df[["agegrp","bp_before"]]

df[10:21]

df.sort_values(by="bp_after",ascending=False,inplace=True)

df

df.loc[8]

df.loc[110,"Name"]

df.iloc[[30],[0,3,4]]

df.loc[50:70,"Name":"Age"]

df['Age'].value_counts()

"""#matplotlib

"""

import matplotlib.pyplot as plt
x = [1,4,3,5,7,234,67]
y= [3,7,435,6,7,4,32]
plt.plot(x,y,marker="*",c="r",linestyle="dashed")
plt.xlabel("xaxis")
plt.ylabel("yaxiz")
plt.show

plt.plot?

plt.scatter(x,y)
plt.xlabel("xlable")
plt.ylabel("ylable")

import numpy as np
x=np.random.randint(1,1000,100)
y=np.random.randint(1,1000,100)
clr=np.random.randint(1,500,100)
siz=np.random.randint(1,500,100)
plt.scatter(x,y,c=clr,s=siz)
plt.title("graph art")
plt.show()

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Copy of bloodp.csv")
df

plt.scatter(df['agegrp'],df['bp_before']) 
plt.xlabel("age")
plt.ylabel("bp before")
plt.title("bp per age")

plt.bar(df['agegrp'],df['bp_before'])

"""#datavis

"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
name=["raju","ramesh","randy","rangu","randi"]
salary=np.random.randint(15000,100000,5)
plt.bar(name,salary,width=0.2)
plt.xlabel("names")
plt.ylabel("salary")
plt.title("salary distributi")

"""#eda"""

import pandas as pd
df=pd.read_csv("/content/train.csv")
df

df.info()

df.describe()

df.isnull().sum()

df['Survived'].sum()



import seaborn as sns
sns.countplot(x="Survived",data=df)

sns.countplot(x="Age",data=df)

import seaborn as sns

sns.catplot(x="Sex",hue="Survived",kind="count",data=df)

sns.catplot(x="Fare",hue="Survived",kind="count",data=df)

sns.violinplot(x="Sex",y="Age",hue="Survived",data=df,split=True)

"""#missing values"""

import numpy as np
a=[1,2,np.nan,np.nan,7,4,np.nan,6]
b=[1,1,1,1,2,2,2,2]
df1=pd.DataFrame({"list1":a,
                  "list2":b})
df1

df1.dropna()

df1

df1.fillna(3)

df1.fillna(df1["list1"].mean())

df1["list1"].fillna(df1.groupby(["list2"])["list1"].transform(np.mean))

import pandas as pd

df = pd.read_excel('/content/reg.xlsx')

df

df = df[df['Pick the Events to be participated'].str.contains('ARCADIA')]

df

df.info()



df.to_excel("reg_bgmi.xlsx")

