# -*- coding: utf-8 -*-
"""seaborn tutorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10zDO1Rvgayg8GYMAU-SbMz8tg03ZVvPN
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/CarPrice_Assignment.csv")

df

ax = sns.scatterplot(x="fueltype",y="citympg",data=df)

ax = sns.scatterplot(x="fueltype",y="citympg",hue="enginetype",data=df)

ax = sns.scatterplot(x="fueltype",y="citympg",hue="enginetype",style="doornumber",data=df)

cmap = cubehelix_palette(dark=3,light=8,as_cmap=True)

ax = sns.scatterplot(x="fueltype",y="citympg",hue="enginetype",style="doornumber",size="enginelocation",sizes=(20,200),palette="Set2",data=df)

ax = sns.relplot(x="fueltype",y="citympg",kind="line",data=df)

ax = sns.relplot(x="fueltype",y="citympg",ci=None,kind="line",data=df)

ax.fig.autofmt_xdate()

ax = sns.relplot(x="fueltype",y="citympg",hue="carbody",ci=None,kind="line",data=df)

ax = sns.relplot(x="fueltype",y="citympg",hue="carbody",style="doornumber",ci=None,kind="line",data=df)

ax = sns.relplot(x="fueltype",y="citympg",hue="carbody",col="wheelbase",row="carlength",height=3,ci=None,kind="line",estimator=None,data=df)

sns.set(style="ticks",color_codes=True)

ax = sns.catplot(x="fueltype",y="citympg",data=df)

ax = sns.catplot(x="fueltype",y="citympg",jitter=False,data=df)

ax = sns.catplot(x="fueltype",y="citympg",hue="doornumber",jitter=False,data=df)

ax = sns.catplot(x="fueltype",y="citympg",kind="box",data=df)

ax = sns.catplot(x="fueltype",y="citympg",hue="doornumber",kind="box",data=df)

diamonds = sns.load_dataset("diamonds")

diamonds

sns.catplot(x="color",y="price",kind="boxen",data=diamonds)

sns.catplot(x="color",y="price",kind="boxen",data=diamonds.sort_values("color"))

sns.catplot(x="color",y="price",hue="cut",kind="violin",data=diamonds)

sns.catplot(x="color",y="price",kind="violin",split="True",data=diamonds)

sns.catplot(x="color",y="price",hue="cut",kind="bar",data=diamonds)

sns.catplot(x="color",y="price",hue="cut",kind="point",data=diamonds)

sns.catplot(x="color",y="clarity",col="cut",aspect=.5,kind="swarm",data=diamonds)

sns.get_dataset_names()

sns.set(style="darkgrid")

tit=sns.load_dataset("titanic")

tit

ax=sns.countplot(x="who",data=tit)

tips = sns.load_dataset("tips")

tips

ax = sns.pointplot(y="total_bill",x="size",data=tips)

ax = sns.pointplot(y="total_bill",x="size",hue="smoker",data=tips)

sns.pointplot(x="tip",y="sex",data=tips)

sns.pointplot(x="tip",y="sex",join=False,data=tips)

ax= sns.boxenplot(x=tips["total_bill"])

ax= sns.boxenplot(x=tips["tip"])

ax=sns.boxenplot(x="day",y="tip",data=tips)

ax = sns.catplot(x="sex",y="total_bill",hue="smoker",col="time",kind="boxen",data=tips)

ax = sns.violinplot(x="sex",y="total_bill",hue="smoker",palette="Set2",split=True,scale="count",data=tips)

ax = sns.violinplot(x="sex",y="total_bill",hue="smoker",palette="Set2",split=True,scale="count",data=tips[tips.total_bill>20])

tips = sns.load_dataset("tips")

tips

ax = sns.boxenplot(x="sex",y="tip",hue="smoker",palette="Set2",data=tips)

ax = sns.boxenplot(x="sex",y="tip",hue="smoker",palette="Set2",data=tips)
ax = sns.stripplot(x="sex",y="tip",hue="smoker",size=4,palette="Set2",data=tips)

ax = sns.violinplot(x=tips["tip"])

ax = sns.violinplot(x="sex",y="tip",order=["Male","Female"],data=tips)

ax = sns.violinplot(x="sex",y="tip",scale="count",order=["Male","Female"],data=tips)

ax = sns.violinplot(x="sex",y="tip",scale="count",order=["Male","Female"],inner="quartile",data=tips)

ax = sns.swarmplot(x=tips["tip"])

ax = sns.swarmplot(x="sex",y="tip",hue="smoker",palette="Set2",data=tips)

ax = sns.swarmplot(x="sex",y="tip",hue="smoker",dodge=True,palette="Set2",data=tips)

ax = sns.catplot(x="sex",y="tip",hue="smoker",dodge=True,palette="Set2",col="time",kind="swarm",height=4,data=tips)

ax = sns.stripplot(x=tips["tip"])

ax = sns.stripplot(x="sex",y="tip",hue="smoker",dodge=True,palette="Set2",data=tips)

ax = sns.stripplot(x="sex",y="tip",hue="smoker",palette="Set2",jitter=True,data=tips)

ax = sns.stripplot(x="sex",y="tip",hue="smoker",palette="Set2",jitter=True,data=tips)
ax = sns.violinplot(x="sex",y="tip",hue="smoker",palette="Set2",data=tips)

ax = sns.catplot(x="sex",y="tip",hue="smoker",dodge=True,palette="Set2",row="time",kind="swarm",height=4,data=tips)

ax = sns.catplot(x="sex",y="tip",hue="smoker",palette="Set2",row="time",kind="bar",height=4,saturation=0.5,ci=None,aspect=0.6,data=tips)
(ax.set_axis_labels("","tips")).set_xticklabels(["male","female"]).set_titles("{row_name},{row_var}").set(ylim=(0,1))

