# -*- coding: utf-8 -*-
"""xgboost_tutorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wiYIHIZdq05vgT5tZBS6kfC30QIzEcY-
"""

pip install xgboost

import sklearn

import xgboost as xgb

from sklearn.datasets import load_iris

iris = load_iris()

samples,features = iris.data.shape

print(samples)
print(features)
print(list(iris.target_names))

from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest = train_test_split(iris.data,iris.target,random_state = 0)

train = xgb.DMatrix(xtrain , label = ytrain)
test = xgb.DMatrix(xtest , label = ytest)

params =  {
    'max_depth':4,
    'eta':0.5,
    'objective':'multi:softmax',
    'num_class':4}
epochs = 14

model = xgb.train(params,train,epochs)

predicta = model.predict(test)

print(predicta)

from sklearn.metrics import accuracy_score

accuracy_score(ytest,predicta)

